spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    #driver-class-name: org.h2.Driver
    url: jdbc:log4jdbc:h2:mem:test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
logging:
  level:
    jdbc:
      resultsettable: info
      sqlonly: info

