spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    #driver-class-name: org.h2.Driver
    url: jdbc:log4jdbc:h2:tcp://localhost/~/test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always
#logging:
#  level:
#    jdbc:
#      sqlonly: info

