@startuml
'https://plantuml.com/activity-diagram-beta

start
:앱에서 해당 차고지 선택;

:차고지 + 시간 가용 차종 가져오기;
:고객이 사용할 수 있는 쿠폰;
'(20개) 빌릴 수 있는것만 가져오는지

:for 각 차종 별로 기본요금;
:레디스 - 차종별 주중 주말, 시즌, 제주, 캠페인...;

:고객 사용할 수 있는 쿠폰 (DB) MST-1000개;
:for(각 쿠폰별 최대 할인 금액 노출);

:부하테스트;
stop

@enduml
