spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl
    username: querydsl
    password: rladudfhd!1
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace